[package]
name = "webthing-vaccine"
version = "0.0.1"
authors = ["DazWilkin <daz.wilkin@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
env_logger = "0.8.2"
log = "0.4.0"
rand = "0.8.0"
serde_json = "1.0.60"
uuid = "0.8.1"
webthing = { version = "0.14" } 
